# _config.yml

# required, replace with your own information -----
title: Data Science + Policy + Ethics
author: Emily Hadley
description: > 
  I'm a data scientist who cares deeply about data, policy, and ethics. I also love hiking, rock climbing, and increasing access to outdoor spaces.
baseurl: emilyhadley.com

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

